name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and test with Docker Compose
      run: |
        echo " POSTGRES_PASSWORD=postgres \ 
        FRONTEND_ORIGIN=http://localhost:5173 \
        JWT_SECRET=${{ secrets.JWT_SECRET }} \ 
        TOKEN_EXPIRES_AT=1h \ 
        GOOGLE_OAUTH_CLIENT_ID=${{ secrets.OAUTH_ID }} \
        GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_SECRET }} \ 
        GOOGLE_OAUTH_REDIRECT_URI=http://localhost:8080/api/sessions/oauth/google" > ./monopoly4u-auth/.env
        docker network create app-network
        git submodule update --init --recursive --remote
        make build
        make test

    - name: Clean up
      run: make clean
