name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and test with Docker Compose
      run: |
        docker network create app-network
        git submodule update --init --recursive --remote
        make build
        make test

    - name: Clean up
      run: make clean
