name: Update from Submodule

on:
  repository_dispatch:
    types: [update-submodule]

jobs:
  update-main-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive # Клонирование с субмодулями

    - name: Configure Git
      run: |
        git config --global user.email "chalkov2002@mail.ru"
        git config --global user.name "juhc"

    - name: Update submodules
      run: |
        git submodule update --init --recursive --remote
        git add .
        git commit -m "Update submodules"
        git push origin HEAD:main --force
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
